language: python

sudo: required

addons:
  chrome: stable

python:
  - 3.6

install:
 - pip install pipenv
 - pipenv install --dev

before_script:
  - python manage.py runserver &

script:
  - python -m unittest discover SGRD/

